"""Task 5：三格式编译器（hbg / cai / cc_skill）—— INTEGRATION §0「单一事实源，多运行时编译」。

编译器契约为控制器 ruling 的固化：
- 返回键 = 相对 --out 的路径（hbg/playbook.py、hbg/system_prompt.md、
  cai/instructions.md、cc_skill/SKILL.md）；
- playbook.py 的 `PLAYBOOK = ` 之后是可 ast.literal_eval 回读的 dict repr，
  且与 entry.model_dump() 逐字段相等；
- 同输入两次编译字节一致（确定性 ruling）。
"""

import ast
from pathlib import Path

from sibylpent.cli import main
from sibylpent.compilers import compile_cai, compile_cc_skill, compile_hbg
from sibylpent.models import PlaybookEntry, ToolEntry, VulnEntry

REPO_ROOT = Path(__file__).resolve().parents[1]
KNOWLEDGE = REPO_ROOT / "knowledge"

GENERATED_MD_MARK = "<!-- generated by sibylctl compile — do not edit -->"
GENERATED_PY_MARK = "# generated by sibylctl compile — do not edit"

ENTRY = PlaybookEntry(
    id="GEN-042",
    domain="generic",
    category="recon",
    check="演示检查：标记回显探测",
    how="向目标提交唯一标记值并归档响应",
    expect_tags=["http_2xx"],
    success_criteria="响应中出现标记值",
    refute_criteria="两条 verify 路径均无标记",
)
TOOL = ToolEntry(
    name="demo-probe",
    url="https://github.com/example/demo-probe",
    phase="recon",
    category="http-probe",
    permission_tier="recon",
    wrap_as="capability",
)
VULN = VulnEntry(
    category="演示类目",
    product="DemoOA",
    name="DemoOA未授权访问",
    url="https://example.com/advisory",
    date="2024.01.01",
    entry_type="vuln",
)
#: 清单行的 ruling 精确格式：`- [GEN-xxx] check — how`
CHECKLIST_LINE = "- [GEN-042] 演示检查：标记回显探测 — 向目标提交唯一标记值并归档响应"


def test_hbg_filenames_markers_and_checklist():
    out = compile_hbg([ENTRY], [TOOL])
    assert set(out) == {"hbg/playbook.py", "hbg/system_prompt.md"}
    assert out["hbg/playbook.py"].startswith(GENERATED_PY_MARK)
    assert out["hbg/system_prompt.md"].startswith(GENERATED_MD_MARK)
    assert "GEN-042" in out["hbg/playbook.py"]
    assert CHECKLIST_LINE in out["hbg/system_prompt.md"]
    assert "## recon" in out["hbg/system_prompt.md"]
    assert "###" not in out["hbg/system_prompt.md"]  # 标题不深于 ##


def test_hbg_playbook_literal_eval_roundtrip():
    text = compile_hbg([ENTRY], [TOOL])["hbg/playbook.py"]
    parsed = ast.literal_eval(text.split("PLAYBOOK = ", 1)[1])
    assert parsed == {"GEN-042": ENTRY.model_dump()}


def test_cai_instructions_three_sections():
    out = compile_cai([ENTRY], [TOOL], [VULN])
    assert set(out) == {"cai/instructions.md"}
    text = out["cai/instructions.md"]
    assert text.startswith(GENERATED_MD_MARK)
    # (a) 类目清单：与 hbg 完全相同的行
    assert CHECKLIST_LINE in text
    # (b) 工具表：name / tier / wrap_as / url
    for needle in (
        "| name | tier | wrap_as | url |",
        "demo-probe",
        "capability",
        "https://github.com/example/demo-probe",
    ):
        assert needle in text
    # (c) 漏洞索引摘要：总数 + 产品（count + 条目名）
    for needle in ("共 1 条", "DemoOA", "DemoOA未授权访问"):
        assert needle in text


def test_cc_skill_frontmatter_and_sections():
    out = compile_cc_skill([ENTRY], [TOOL], [VULN])
    assert set(out) == {"cc_skill/SKILL.md"}
    text = out["cc_skill/SKILL.md"]
    lines = text.splitlines()
    # 控制器裁定：SKILL.md 豁免首行标记——frontmatter 必须位于文件首行
    # （Claude Code 只在 --- 是第一行时才解析 name/description），生成标记
    # 紧随 frontmatter 结束的 --- 之后。
    assert lines[0] == "---"
    assert lines[1] == "name: sibylpent-generic"
    assert lines[2].startswith("description:")
    assert lines[3] == "---"
    assert lines[4] == GENERATED_MD_MARK
    for needle in (
        "## Playbook Checklist",
        "## Tools",
        "## Known Vulns",
        CHECKLIST_LINE,
        "demo-probe",
        "DemoOA未授权访问",
    ):
        assert needle in text


def test_compilers_are_deterministic():
    # 值相同的新对象（非同一实例）→ 输出必须字节一致
    entry2 = PlaybookEntry.model_validate(ENTRY.model_dump())
    tool2 = ToolEntry.model_validate(TOOL.model_dump())
    vuln2 = VulnEntry.model_validate(VULN.model_dump())
    assert compile_hbg([ENTRY], [TOOL]) == compile_hbg([entry2], [tool2])
    assert compile_cai([ENTRY], [TOOL], [VULN]) == compile_cai([entry2], [tool2], [vuln2])
    assert compile_cc_skill([ENTRY], [TOOL], [VULN]) == compile_cc_skill(
        [entry2], [tool2], [vuln2]
    )


def test_cli_compile_real_knowledge_deterministic(tmp_path):
    out_a, out_b = tmp_path / "gen-a", tmp_path / "gen-b"
    assert main(["compile", "--knowledge", str(KNOWLEDGE), "--out", str(out_a)]) == 0
    assert main(["compile", "--knowledge", str(KNOWLEDGE), "--out", str(out_b)]) == 0
    for rel in (
        "hbg/playbook.py",
        "hbg/system_prompt.md",
        "cai/instructions.md",
        "cc_skill/SKILL.md",
    ):
        assert (out_a / rel).is_file()
        assert (out_a / rel).read_bytes() == (out_b / rel).read_bytes()


def test_cli_compile_fails_on_missing_knowledge(tmp_path):
    rc = main(
        [
            "compile",
            "--knowledge", str(tmp_path / "nope"),
            "--out", str(tmp_path / "gen"),
        ]
    )
    assert rc == 1
