"""编译器共享构件：生成标记与三类内容体（检查清单 / 工具表 / 漏洞摘要）。

约定（M0 Task 5）：
- 编译器返回 {相对 --out 的路径: 文件内容}，由 cli 的 compile 子命令落盘；
- 全部纯函数 + 确定性排序：同一输入 → 字节相同输出。
"""

from collections import Counter

from sibylpent.models import PlaybookEntry, ToolEntry, VulnEntry

#: 生成文件首行标记（markdown 用 HTML 注释，playbook.py 用 # 注释）
GENERATED_MARKDOWN = "<!-- generated by sibylctl compile — do not edit -->"
GENERATED_PYTHON = "# generated by sibylctl compile — do not edit"

#: checklist 分组顺序：已知类目按渗透流程排，未知类目字典序殿后
_KNOWN_CATEGORIES = ("recon", "authz", "injection")
#: 权限档位顺序（INTEGRATION 档位映射：recon < scan < exploit < destructive）
_TIER_ORDER = ("recon", "scan", "exploit", "destructive")

#: 漏洞摘要参数：至多 10 个产品，每产品至多列 3 个条目名
VULN_TOP_PRODUCTS = 10
VULN_NAMES_PER_PRODUCT = 3


def checklist_sections(
    entries: list[PlaybookEntry], heading: str = "###"
) -> list[str]:
    """按类目分组的清单体（不带总节标题）；组内保持条目原序。"""
    grouped: dict[str, list[PlaybookEntry]] = {}
    for entry in entries:
        grouped.setdefault(entry.category, []).append(entry)
    ordered = sorted(
        grouped.items(),
        key=lambda item: (
            _KNOWN_CATEGORIES.index(item[0])
            if item[0] in _KNOWN_CATEGORIES
            else len(_KNOWN_CATEGORIES),
            item[0],
        ),
    )
    lines: list[str] = []
    for category, cat_entries in ordered:
        lines += [f"{heading} {category}", ""]
        lines += checklist_lines(cat_entries)
        lines.append("")
    return lines


def checklist_lines(entries: list[PlaybookEntry]) -> list[str]:
    """每个条目一行 `- [GEN-xxx] check — how`（hbg/cai/cc_skill 三格式共用）。"""
    return [f"- [{e.id}] {e.check} — {e.how}" for e in entries]


def tool_table(tools: list[ToolEntry]) -> list[str]:
    """工具档位表（name / tier / wrap_as / url），按档位低→高 + 名称排序。"""
    ordered = sorted(
        tools,
        key=lambda t: (
            _TIER_ORDER.index(t.permission_tier)
            if t.permission_tier in _TIER_ORDER
            else len(_TIER_ORDER),
            t.name,
        ),
    )
    rows = [f"| {t.name} | {t.permission_tier} | {t.wrap_as} | {t.url} |" for t in ordered]
    return ["| name | tier | wrap_as | url |", "| --- | --- | --- | --- |"] + rows


def vuln_summary_lines(vulns: list[VulnEntry]) -> list[str]:
    """漏洞索引摘要：总条数 + 按产品条目数 Top-N（count + 至多 3 个条目名）。"""
    counts: Counter[str] = Counter(v.product for v in vulns)
    examples: dict[str, list[str]] = {}
    for v in vulns:  # 按索引加载顺序取每产品前几个条目名，保证确定性
        names = examples.setdefault(v.product, [])
        if len(names) < VULN_NAMES_PER_PRODUCT:
            names.append(v.name)
    top = sorted(counts, key=lambda p: (-counts[p], p))[:VULN_TOP_PRODUCTS]
    lines = [
        f"索引共 {len(vulns)} 条条目；按产品条目数排序，"
        f"至多列前 {VULN_TOP_PRODUCTS} 个产品："
    ]
    for product in top:
        names = "；".join(examples[product])
        ellipsis = "；…" if counts[product] > VULN_NAMES_PER_PRODUCT else ""
        lines.append(f"- {product}（{counts[product]} 条）：{names}{ellipsis}")
    return lines
